Fix failure in building of perl integration source for 9.2 on macOS
Building the previous formula led to the following error in the make step:

    In file included from plperl.c:49:
    ./plperl.h:53:10: fatal error: 'EXTERN.h' file not found
    #include "EXTERN.h"
             ^~~~~~~~~~

As of XCode 10(?), system headers have been removed from the base macOS system
and now only live in the macOS SDK, which must be included explicitly for the
build process to find the system perl headers that were previously expected
to already be globally available.

See these links for more info:
* https://apple.stackexchange.com/questions/337940/
* https://developer.apple.com/documentation/xcode_release_notes/xcode_10_release_notes#3035623